// Phase 2 --- H^s-preconditioned gradient flow demo.
//
// Same setup as Phase 1: Barnes-Hut TPE on an ellipsoid generated by scaling
// icosphere(2), then normalizing. We still remove the scale mode and renormalize
// after each accepted step, but now we use the core H^s preconditioner API to
// compute the descent direction.
//
// Line search uses frozen-partition semantics: per outer iteration, build
// (BVH, BCT) once from the current mesh, then during Armijo backtracking keep
// that partition fixed and only refresh BVH aggregates on trial geometries.
//
// Outputs: out/phase2_hs_flow/frame_XXXX.obj and energy.csv with
// (iter, energy, grad_norm, step_size, n_backtracks, g_dot_dir).

#include "BCT.h"
#include "BVH.h"
#include "Constraints.h"
#include "FaceGeom.h"
#include "HsPreconditioner.h"
#include "MeshData.h"
#include "TPE.h"
#include "TestMeshes.h"

#include <Eigen/Dense>
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <sstream>
#include <stdexcept>
#include <string>

using rsh::MeshData;

namespace {

std::string frame_path(const std::string &dir, int idx) {
    std::ostringstream oss;
    oss << dir << "/frame_" << std::setfill('0') << std::setw(4) << idx << ".obj";
    return oss.str();
}

void remove_stale_frames(const std::string &dir) {
    if (!std::filesystem::exists(dir)) return;
    for (const auto &entry : std::filesystem::directory_iterator(dir)) {
        if (!entry.is_regular_file()) continue;
        const std::string name = entry.path().filename().string();
        if (name.rfind("frame_", 0) == 0 && entry.path().extension() == ".obj") {
            std::filesystem::remove(entry.path());
        }
    }
}

double parse_initial_tau(int argc, char **argv) {
    double initial_tau = 1.0;
    for (int i = 1; i < argc; ++i) {
        const std::string arg = argv[i];
        if (arg == "--initial-tau" || arg == "--tau0") {
            if (i + 1 >= argc) {
                throw std::runtime_error(arg + " requires a numeric value");
            }
            initial_tau = std::stod(argv[++i]);
        } else if (arg.rfind("--initial-tau=", 0) == 0) {
            initial_tau = std::stod(arg.substr(std::string("--initial-tau=").size()));
        } else if (arg.rfind("--tau0=", 0) == 0) {
            initial_tau = std::stod(arg.substr(std::string("--tau0=").size()));
        } else {
            throw std::runtime_error("unknown argument: " + arg);
        }
    }

    if (!std::isfinite(initial_tau) || initial_tau <= 0.0) {
        throw std::runtime_error("--initial-tau must be positive and finite");
    }
    return initial_tau;
}

void remove_scale_mode(const Eigen::MatrixXd &V, Eigen::MatrixXd &G) {
    const Eigen::RowVector3d c = V.colwise().mean();
    const Eigen::MatrixXd R = V.rowwise() - c;
    const double den = R.squaredNorm();
    if (den > 0.0) {
        const double num = R.cwiseProduct(G).sum();
        G -= (num / den) * R;
    }
}

void scale_axes(MeshData &m, double sx, double sy, double sz) {
    m.V.col(0) *= sx;
    m.V.col(1) *= sy;
    m.V.col(2) *= sz;
}

} // namespace

int main(int argc, char **argv) {
    const int ico_subdiv = 2;
    const double sx = 1.7, sy = 0.75, sz = 0.75;
    const double alpha = 6.0;
    const double theta = 0.0;
    const double hs_s = 1.5;
    const double hs_sigma = 1.0;
    const double hs_mass_weight = 1.0;
    const int max_iters = 1000;
    const double armijo_c1 = 1e-4;
    const double shrink = 0.5;
    const int max_backtracks = 60;
    const double grad_tol = 1e-6;
    const double rel_progress_tol = 1e-6;
    const int stall_window = 5;
    const double initial_tau = parse_initial_tau(argc, argv);

    const std::string out_dir = "out/phase2_hs_flow";
    std::filesystem::create_directories(out_dir);
    remove_stale_frames(out_dir);

    MeshData m = rsh::make_icosphere(ico_subdiv);
    scale_axes(m, sx, sy, sz);
    m.normalize();

    auto bbox_extents = [](const MeshData &mesh) {
        const Eigen::Vector3d mn = mesh.V.colwise().minCoeff();
        const Eigen::Vector3d mx = mesh.V.colwise().maxCoeff();
        return (mx - mn).eval();
    };

    const Eigen::Vector3d ext0 = bbox_extents(m);
    std::cout << "Phase 2 demo --- H^s-preconditioned flow on ellipsoid (icosphere(" << ico_subdiv << ") scaled)\n"
              << "  n_v = " << m.n_vertices()
              << ", n_f = " << m.n_faces() << "\n"
              << "  axis scales: (" << sx << ", " << sy << ", " << sz << ")\n"
              << "  s = " << hs_s << ", alpha = " << alpha << ", theta = " << theta << "\n"
              << "  hs_sigma = " << hs_sigma
              << ", hs_mass_weight = " << hs_mass_weight << "\n"
              << "  initial Armijo trial tau = " << initial_tau << "\n"
              << "  initial bbox extents: (" << ext0(0) << ", "
              << ext0(1) << ", " << ext0(2) << ")\n"
              << "  round sphere target:  (0.5774, 0.5774, 0.5774)\n"
              << "  output: " << out_dir << "/\n\n";

    std::ofstream csv(out_dir + "/energy.csv");
    csv << "iter,energy,grad_norm,step_size,n_backtracks,g_dot_dir\n";

    m.save_obj(frame_path(out_dir, 0));

    const rsh::HsPreconditionerParams hs_params{hs_s, hs_sigma, hs_mass_weight};
    rsh::HsConstraints hs_constraints;
    hs_constraints.pin_barycenter = true;
    const Eigen::RowVector3d initial_centroid = m.V.colwise().mean();
    double tau = initial_tau;
    double E_stall_ref = std::numeric_limits<double>::infinity();
    int stall_ref_iter = -stall_window;

    for (int it = 0; it < max_iters; ++it) {
        const rsh::FaceGeom g = rsh::compute_face_geom(m);
        const rsh::BVH bvh = rsh::build_bvh(m, g);
        const rsh::BlockPairs bp = rsh::build_bct_self(bvh, theta);

        const double E = rsh::tpe_energy_bh(g, bvh, bp, alpha);
        Eigen::MatrixXd G = rsh::tpe_gradient_bh(m, g, bvh, bp, alpha);
        remove_scale_mode(m.V, G);
        const double gnorm2 = G.squaredNorm();
        const double gnorm = std::sqrt(gnorm2);

        if (gnorm < grad_tol) {
            std::cout << "  gradient below tol --- stopped at iter " << it << "\n";
            csv << it << "," << E << "," << gnorm << ",0,0,0\n";
            break;
        }

        const rsh::HsDirectionResult hs =
            rsh::hs_preconditioned_direction(m, G, hs_params, hs_constraints);
        tau = std::min(tau * 2.0, initial_tau);
        int n_bt = 0;
        MeshData m_try = m;
        rsh::BVH bvh_try = bvh;
        double E_new = E;
        for (; n_bt < max_backtracks; ++n_bt) {
            m_try.V = m.V - tau * hs.direction;
            m_try.normalize();
            const rsh::FaceGeom g_try = rsh::compute_face_geom(m_try);
            rsh::update_bvh_aggregates(bvh_try, g_try);
            E_new = rsh::tpe_energy_bh(g_try, bvh_try, bp, alpha);
            if (E_new <= E - armijo_c1 * tau * hs.g_dot_dir) break;
            tau *= shrink;
        }

        if (n_bt == max_backtracks) {
            std::cout << "  Armijo failed at iter " << it << " --- stopping\n";
            break;
        }

        m = m_try;

        std::printf("iter %3d  E = %.6e  |g| = %.3e  g.d = %.3e  tau = %.3e  bt = %2d\n",
                    it, E, gnorm, hs.g_dot_dir, tau, n_bt);
        csv << it << "," << E << "," << gnorm << "," << tau << "," << n_bt
            << "," << hs.g_dot_dir << "\n";
        csv.flush();

        m.save_obj(frame_path(out_dir, it + 1));

        if (it - stall_ref_iter >= stall_window) {
            const double rel = (E_stall_ref - E_new) / std::max(std::abs(E_stall_ref), 1.0);
            if (rel < rel_progress_tol) {
                std::cout << "  relative progress < " << rel_progress_tol
                          << " over " << stall_window
                          << " iters --- stopping\n";
                break;
            }
            E_stall_ref = E_new;
            stall_ref_iter = it;
        }
    }

    const Eigen::Vector3d extF = bbox_extents(m);
    const double barycenter_drift =
        (m.V.colwise().mean() - initial_centroid).norm();
    std::cout << "\nfinal bbox extents:   (" << extF(0) << ", "
              << extF(1) << ", " << extF(2) << ")\n"
              << "barycenter drift: " << barycenter_drift << "\n"
              << "Frames: " << out_dir << "/frame_*.obj\n"
              << "Energy log: " << out_dir << "/energy.csv\n";
    return 0;
}
